name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: build docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      - name: dockerhub login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login - u $DOCKER_USER -p $DOCKER_PASSWORD
      
      - name: dockerhub push
        run: docker push ${{secrets.DOCKER_USER}}/vitepress_local_wiki
